---
title: Domini's Blog
timezone: Europe/Chisinau
collections:
  uploads:
    title: Uploads
    output: true
  domini:
    title: domini
    output: true
  people:
    title: people
    output: true
  posts:
    title: Статьи
    output: true
lang: ru_RU
locale: ru_RU
email: transgregorial@gmail.com
#description: Экспертный блог о промышленной инженерии, системной инженерии,  науке
#  о данных и искусственном интеллекте. Практические руководства,  аналитика и инструменты
#  для профессионалов.
description: >-
  An expert blog on industrial engineering, systems engineering,
  data science, and artificial intelligence. Practical guides,.
  analytics, and tools for professionals.

url: https://dominicusin.github.io
theme: minima
twitter_username: dominicusin
github_username: dominicusin
permalink: "/:year/:month/:day/:title/"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor
- README.md
- LICENSE
- ".gitignore"
- ".github"
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Manifest.md
sass:
  style: compressed
author:
  name: Domini
  orcid: 0000-0002-7425-0526
  github: dominicusin
  email: transgregorial@gmail.com
  twitter: dominicusin
social:
- name: GitHub
  url: https://github.com/dominicusin
  icon: github
- name: Twitter
  url: https://twitter.com/dominicusin
  icon: twitter
navigation:
- name: Home
  url: "/"
- name: About
  url: "/about/"
- name: Posts
  url: "/posts/"
- name: Archive
  url: "/archive/"
paginate: 10
paginate_path: "/page:num/"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
safe: true
