---
title: Domini's blog
timezone: Europe/Helsinki
collections:
  uploads:
    title: Uploads
    output: true
  domini:
    title: domini
    output: true
  posts:
    title: Статьи
    output: true
email: transgregorial@gmail.com
description: "**personal site, blog Domini**"
url: https://dominicusin.github.io/
twitter_username: dominicusin
github_username: dominicusin
Field name: 
markdown: kramdown
