---
title: Список фильмов
timezone: Europe/Moscow
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Статьи
    output: true
email: dominidomini@mail.ru
description: Пробный сайт
baseurl: 
url: https://dominicusin.github.io/
twitter_username: dominicusin
github_username: dominicusin
markdown: kramdown
