---
title: Domini's blog
timezone: Europe/Helsinki
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Статьи
    output: true
email: transgregorial@gmail.com
description: личный сайт, блог Domini
baseurl: 
url: https://dominicusin.github.io/
twitter_username: dominicusin
github_username: dominicusin
markdown: kramdown
